spring.datasource.url=jdbc:h2:mem:usuarios-db

spring.rabbitmq.addresses=amqps://szpkdtyp:RvhMFET8uIbfELRSLtDdPcE3-HqfBU7N@jackal.rmq.cloudamqp.com/szpkdtyp

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=caririprint@gmail.com
spring.mail.password=knur akta lpzx nktv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true